# -*- coding: utf-8 -*-
"""App_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SsMN691OwBKjFrdlO9QTR3BnfUYO2mxD
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

# --- CONFIGURACIÓN DE PÁGINA (Estilo Alan) ---
st.set_page_config(
    page_title="Alan Health Spain - Reporting Actuarial & Business",
    page_icon="💜",
    layout="wide"
)

# --- ESTILOS CSS PERSONALIZADOS (Alineado con format.png) ---
st.markdown("""
<style>
    /* Fondo principal y textos */
    .stApp {
        background-color: #FFFFFF; /* Fondo blanco limpio */
        color: #111827; /* Texto gris muy oscuro */
    }
    h1 {
        color: #111827 !important;
        font-weight: 700;
        text-align: center;
        margin-bottom: 30px;
    }
    h3 {
        color: #111827 !important;
        font-weight: 600;
        margin-top: 20px;
    }
    .stMarkdown p {
        text-align: center;
        color: #6B7280; /* Gris secundario */
        font-size: 1.1em;
    }

    /* Estilo para las Tarjetas de Métricas (KPIs) */
    div[data-testid="stMetricValue"] {
        background-color: #F8FAFC; /* Fondo muy claro para tarjeta */
        border: 1px solid #E2E8F0; /* Borde sutil */
        border-radius: 12px;
        padding: 20px;
        text-align: center;
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03);
    }
    div[data-testid="stMetricLabel"] p {
        color: #6B7280;
        font-size: 0.9em;
        font-weight: 500;
    }
    div[data-testid="stMetricValue"] {
        color: #7C3AED !important; /* Violeta Alan para el valor principal */
        font-size: 2.2em !important;
        font-weight: 700 !important;
    }
    /* Estilo del delta (Target) */
    div[data-testid="stMetricDelta"] > div {
        background-color: #F8FAFC; /* Fondo claro para delta */
    }

    /* Sidebar - Estilo Alan */
    [data-testid="stSidebar"] {
        background-color: #F8FAFC;
        border-right: 1px solid #E2E8F0;
    }
    [data-testid="stSidebar"] h2, [data-testid="stSidebar"] h3 {
        color: #7C3AED !important; /* Violeta Alan para títulos sidebar */
    }

    /* Botones y Sliders */
    .stButton>button {
        background-color: #7C3AED;
        color: white;
        border-radius: 8px;
    }
    div[data-baseweb="slider"] {
        color: #7C3AED !important;
    }

    /* Separadores y Tablas */
    hr {
        border: 0;
        border-top: 1px solid #E2E8F0;
    }
    .stTable {
        border-radius: 12px;
        overflow: hidden;
        border: 1px solid #E2E8F0;
    }
    .stTable thead tr th {
        background-color: #F1F5F9;
        color: #475569;
    }
</style>
""", unsafe_allow_html=True)

# --- HEADER: LOGO Y TÍTULO (Marca Personal) ---
# Integramos el logo de Alan proporcionado
logo_url = "image_1.png"
col_logo, col_title = st.columns([1, 6])
with col_logo:
    st.image(logo_url, width=150)
with col_title:
    st.title("Reporting Mensual de Rentabilidad y Drivers Actuariales")

st.markdown("""
Framework de reporting interno mensual diseñado bajo los principios de **transparencia radical** de Alan.
Permite monitorizar la cuenta de resultados técnica, los *Key Actuarial Drivers* y la rentabilidad por segmento y producto.
""")

# --- SIDEBAR: CONTEXTO Y OFERTAS OFICIALES DE ALAN ---
st.sidebar.header("🏢 Segmento de Cliente")
segmento = st.sidebar.radio("Tipo de Cliente", ["Empresas (B2B)", "Individuales / TNS (B2C)"])

if segmento == "Empresas (B2B)":
    # Mantenemos los mismos campos pero el estilo es más limpio
    plan = st.sidebar.selectbox("Oferta B2B (Elegible Colectivos)", ["Essentiel", "Balanced", "Optimal"])
    num_miembros = st.sidebar.slider("Número de Asegurados en Colectivo", min_value=50, max_value=10000, value=1000, step=50)
    edad_media = st.sidebar.slider("Edad Media de la Plantilla", min_value=20, max_value=65, value=36)

    # Primas base estimadas B2B (Mismos valores)
    prima_base = {"Essentiel": 38.0, "Balanced": 52.0, "Optimal": 75.0}[plan]
    # Factor demográfico actuarial B2B (Mismo cálculo)
    factor_demog = 1.0 + max(0, (edad_media - 30) * 0.015)
    prima_mes = prima_base * factor_demog
else:
    plan = st.sidebar.selectbox("Oferta B2C", ["Alan Rubis", "Alan Emeraude", "Alan Saphir"])
    num_miembros = st.sidebar.slider("Número de Asegurados Individuales", min_value=50, max_value=3000, value=500, step=25)
    # Primas base B2C (Mismos valores)
    prima_mes = {"Alan Rubis": 42.0, "Alan Emeraude": 65.0, "Alan Saphir": 95.0}[plan]
    factor_demog = 1.0

st.sidebar.header("📊 Drivers de Siniestralidad y Reservas")
frecuencia_reclamos = st.sidebar.slider("Frecuencia (Reclamos / Mes)", min_value=0.2, max_value=2.0, value=0.65, step=0.05)
costo_medio_reclamo = st.sidebar.number_input("Costo Medio por Reclamo (€)", min_value=20.0, max_value=300.0, value=58.0, step=2.0)

# Reservas Actuariales (Mismos valores)
rbns_pct = st.sidebar.slider("Reserva RBNS (% Siniestros Notificados)", min_value=1.0, max_value=8.0, value=3.0, step=0.5) / 100.0
ibnr_pct = st.sidebar.slider("Reserva IBNR (% Siniestros Incurridos)", min_value=1.0, max_value=10.0, value=4.5, step=0.5) / 100.0
adopcion_prevencion = st.sidebar.slider("Adopción Salud Digital (%)", min_value=10, max_value=100, value=55, step=5) / 100.0

st.sidebar.header("💸 Cargas de Gastos (% Prima)")
comisiones_pct = st.sidebar.slider("Comisiones / Adquisición (%)", min_value=0.0, max_value=15.0, value=4.5, step=0.5) / 100.0
operaciones_admin_pct = st.sidebar.slider("Gastos Admin & Operaciones (%)", min_value=5.0, max_value=20.0, value=9.5, step=0.5) / 100.0
reaseguro_pct = st.sidebar.slider("Costo de Reaseguro (%)", min_value=0.5, max_value=5.0, value=1.5, step=0.1) / 100.0

# --- CÁLCULOS ACTUARIALES (Lógica sin cambios) ---
ingresos_primas_mes = num_miembros * prima_mes

# Siniestralidad
siniestros_pagados_base = num_miembros * frecuencia_reclamos * costo_medio_reclamo
reduccion_prevencion = adopcion_prevencion * 0.07
siniestros_pagados = siniestros_pagados_base * (1.0 - reduccion_prevencion)

rbns_monto = siniestros_pagados * rbns_pct
ibnr_monto = (siniestros_pagados + rbns_monto) * ibnr_pct
siniestros_totales_incurridos = siniestros_pagados + rbns_monto + ibnr_monto

# Gastos Operativos y Adquisición
comisiones_monto = ingresos_primas_mes * comisiones_pct
gastos_admin_monto = ingresos_primas_mes * operaciones_admin_pct
reaseguro_monto = ingresos_primas_mes * reaseguro_pct
gastos_totales_monto = comisiones_monto + gastos_admin_monto + reaseguro_monto

# Márgenes y Ratios Actuariales
margen_tecnico_bruto = ingresos_primas_mes - siniestros_totales_incurridos
resultado_tecnico_neto = margen_tecnico_bruto - gastos_totales_monto

loss_ratio = (siniestros_totales_incurridos / ingresos_primas_mes) if ingresos_primas_mes > 0 else 0
expense_ratio = (gastos_totales_monto / ingresos_primas_mes) if ingresos_primas_mes > 0 else 0
combined_ratio = loss_ratio + expense_ratio
auto_claims_rate = min(0.96, 0.82 + (adopcion_prevencion * 0.12))

# --- TARJETAS DE MÉTRICAS CLAVE (KPIs) - Mismos Campos, Nuevo Formato ---
st.divider()
col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric("Primas Devengadas", f"{ingresos_primas_mes:,.0f} €", help="Total primas estimadas para el periodo actual.")
with col2:
    st.metric("Loss Ratio Incurrido (S/P)", f"{loss_ratio:.1%}", delta="Target <78%", delta_color="inverse", help="Siniestralidad Total Incurrida sobre Primas.")
with col3:
    st.metric("Combined Ratio Total", f"{combined_ratio:.1%}", delta=f"{'Superávit' if combined_ratio < 1 else 'Déficit'}", delta_color="inverse", help="Siniestralidad + Gastos sobre Primas. Objetivo <90%.")
with col4:
    st.metric("Resultado Técnico Neto", f"{resultado_tecnico_neto:,.0f} €", help="Margen final tras siniestros y todos los gastos operativos.")

st.divider()

# --- DASHBOARD VISUAL (Mismos Gráficos, Colores Alan) ---
col_left, col_right = st.columns(2)

with col_left:
    st.subheader("Desglose de la Cuenta de Resultados (P&L)")
    conceptos = ["Primas Devengadas", "Siniestros Pagados", "Reserva RBNS", "Reserva IBNR", "Gastos Op. & CAC", "Resultado Neto"]
    valores = [ingresos_primas_mes, -siniestros_pagados, -rbns_monto, -ibnr_monto, -gastos_totales_monto, resultado_tecnico_neto]
    df_pnl = pd.DataFrame({"Concepto": conceptos, "Monto (€)": valores})

    # Actualizamos colores: Violeta para ingresos/resultado positivo, Rojo para gastos.
    colors_pnl = ['#7C3AED', '#EF4444', '#F87171', '#FCA5A5', '#FECACA', '#00D47E' if resultado_tecnico_neto > 0 else '#EF4444']

    fig_pnl = px.bar(df_pnl, x="Concepto", y="Monto (€)", color="Concepto",
                     color_discrete_sequence=colors_pnl, text_auto=".1s")

    fig_pnl.update_layout(
        showlegend=False,
        xaxis_title="",
        yaxis_title="",
        plot_bgcolor='rgba(0,0,0,0)',
        paper_bgcolor='rgba(0,0,0,0)',
        font_color="#6B7280"
    )
    fig_pnl.update_traces(textposition='outside')
    st.plotly_chart(fig_pnl, use_container_width=True)

with col_right:
    st.subheader("Sensibilidad Combined Ratio vs Adopción Preventiva")
    adop_range = np.linspace(0.1, 1.0, 10)
    lr_range = [((siniestros_pagados_base * (1 - (a * 0.07))) * (1 + rbns_pct) * (1 + ibnr_pct)) / (num_miembros * prima_mes) for a in adop_range]
    cr_range = [lr + expense_ratio for lr in lr_range]

    df_cr = pd.DataFrame({"Adopción Salud Digital (%)": adop_range * 100, "Combined Ratio (%)": np.array(cr_range) * 100})

    # Línea principal en Violeta Alan
    fig_cr = px.line(df_cr, x="Adopción Salud Digital (%)", y="Combined Ratio (%)", markers=True, color_discrete_sequence=["#7C3AED"])

    fig_cr.add_hline(y=100, line_dash="dash", line_color="#EF4444", annotation_text="Breakeven (100%)", annotation_position="bottom right")
    fig_cr.add_hline(y=90, line_dash="dash", line_color="#00D47E", annotation_text="Target Alan (90%)", annotation_position="top right")

    fig_cr.update_layout(
        xaxis_title="Adopción Salud Digital (%)",
        yaxis_title="Combined Ratio (%)",
        plot_bgcolor='rgba(0,0,0,0)',
        paper_bgcolor='rgba(0,0,0,0)',
        font_color="#6B7280"
    )
    st.plotly_chart(fig_cr, use_container_width=True)

# --- TABLA DE RESUMEN (Mismos Campos, Nuevo Formato) ---
st.subheader("Resumen de Ratios Actuariales y Financieros")
ratios_df = pd.DataFrame({
    "Ratio Actuarial": ["Loss Ratio Incurrido (S/P)", "Expense Ratio (Gastos/Primas)", "Combined Ratio (LR + ER)", "Tasa Auto-claims"],
    "Valor": [f"{loss_ratio:.2%}", f"{expense_ratio:.2%}", f"{combined_ratio:.2%}", f"{auto_claims_rate:.1%}"],
    "Benchmark / Target": ["< 78.0%", "< 12.0%", "< 90.0%", "> 90.0%"],
    "Estado": ["✅ En Rango" if loss_ratio <= 0.78 else "⚠️ Revisar Tarifa",
               "✅ Eficiente" if expense_ratio <= 0.12 else "⚠️ Alto G&A", # Ajusté target ER a 12% como dice el benchmark
               "🟢 Rentable" if combined_ratio <= 1.0 else "🔴 En Pérdida",
               "🟢 Objetivo Cumplido" if auto_claims_rate >= 0.9 else "🟡 Mejorar Adopción"]
})

# Mostrar tabla usando markdown para aplicar estilos CSS
st.markdown(ratios_df.to_html(index=False, escape=False, classes='stTable'), unsafe_allow_html=True)

# --- FOOTER ---
st.divider()
st.caption("Alan Health Spain Insurance - Framework Actuarial y de Producto v3.1 | Datos Simulados para demostración.")