{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7fabcda4-4c8d-42d1-a0e5-a7f28703f05f",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-07-29 11:38:47.916 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:47.917 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.071 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run /opt/conda/envs/anaconda-2025.12-py312/lib/python3.12/site-packages/ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-07-29 11:38:48.071 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.072 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.073 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.073 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.074 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.074 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.074 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.075 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.075 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.076 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.076 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.077 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.077 Session state does not function when running a script without `streamlit run`\n",
      "2026-07-29 11:38:48.078 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.078 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.079 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.079 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.080 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.080 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.081 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.081 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.082 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.082 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.083 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.083 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.084 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.084 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.085 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.085 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.086 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.086 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.086 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.087 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.087 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.088 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.088 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.089 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.089 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.090 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.090 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.091 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.091 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.092 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.093 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.093 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.094 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.094 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.095 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.095 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.096 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.096 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.096 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.097 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.097 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.098 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.098 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.098 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.099 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.100 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.100 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.101 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.101 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.102 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.106 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.106 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.107 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.107 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.108 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.108 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.109 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.110 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.110 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.111 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.111 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.111 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.112 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.112 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.113 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.114 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.114 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.114 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.250 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2026-07-29 11:38:48.254 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.254 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.255 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.255 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.256 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.257 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.257 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.278 Please replace `use_container_width` with `width`.\n",
      "\n",
      "`use_container_width` will be removed after 2025-12-31.\n",
      "\n",
      "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
      "2026-07-29 11:38:48.279 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.280 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.280 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.280 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.281 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.281 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.282 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-07-29 11:38:48.282 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import plotly.express as px\n",
    "\n",
    "st.set_page_config(\n",
    "    page_title=\"Alan Health - Monthly Actuarial & Business Reporting\",\n",
    "    page_icon=\"💚\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "st.title(\"💚 Alan Health: Reporting Mensual de Rentabilidad y Drivers Actuariales\")\n",
    "st.markdown(\"\"\"\n",
    "Dashboard interno alineado con el principio de **transparencia radical** de Alan [cited: 3]. \n",
    "Permite monitorizar los *key actuarial drivers* y la rentabilidad por segmento de cliente y oferta [cited: 35].\n",
    "\"\"\")\n",
    "\n",
    "st.sidebar.header(\"🏢 Filtros del Segmento de Cliente\")\n",
    "\n",
    "segmento = st.sidebar.radio(\"Tipo de Cliente\", [\"Empresas (B2B)\", \"Individuales / TNS (B2C)\"])\n",
    "\n",
    "if segmento == \"Empresas (B2B)\":\n",
    "    plan = st.sidebar.selectbox(\"Oferta B2B\", [\"Essentiel\", \"Balanced\", \"Optimal\"])\n",
    "    num_miembros = st.sidebar.slider(\"Número de Miembros Asegurados\", min_value=50, max_value=5000, value=500, step=50)\n",
    "    edad_media = st.sidebar.slider(\"Edad Media de la Plantilla (Ajuste Demográfico)\", min_value=22, max_value=60, value=35)\n",
    "    prima_base = {\"Essentiel\": 38.0, \"Balanced\": 52.0, \"Optimal\": 75.0}[plan]\n",
    "    # Factor demográfico: +1.5% por cada año por encima de 30 años\n",
    "    factor_demog = 1.0 + max(0, (edad_media - 30) * 0.015)\n",
    "    prima_mes = prima_base * factor_demog\n",
    "else:\n",
    "    plan = st.sidebar.selectbox(\"Oferta B2C\", [\"Alan Rubis\", \"Alan Emeraude\", \"Alan Saphir\"])\n",
    "    num_miembros = st.sidebar.slider(\"Número de Asegurados Individuales\", min_value=50, max_value=2000, value=300, step=25)\n",
    "    prima_mes = {\"Alan Rubis\": 42.0, \"Alan Emeraude\": 65.0, \"Alan Saphir\": 95.0}[plan]\n",
    "    factor_demog = 1.0\n",
    "\n",
    "st.sidebar.header(\"📊 Drivers Actuariales Mensuales\")\n",
    "frecuencia_reclamos = st.sidebar.slider(\"Frecuencia (Reclamos / Miembro / Mes)\", min_value=0.2, max_value=2.0, value=0.6, step=0.05)\n",
    "costo_medio_reclamo = st.sidebar.number_input(\"Costo Medio por Reclamo (€)\", min_value=20.0, max_value=300.0, value=55.0, step=5.0)\n",
    "adopcion_prevencion = st.sidebar.slider(\"Adopción Salud Digital / Prevención (%)\", min_value=10, max_value=100, value=50, step=5) / 100.0\n",
    "\n",
    "# Cálculos Mensuales\n",
    "ingresos_primas_mes = num_miembros * prima_mes\n",
    "siniestros_incurridos_mes = num_miembros * frecuencia_reclamos * costo_medio_reclamo\n",
    "# Reducción por prevención activa\n",
    "reduccion_prevencion = adopcion_prevencion * 0.06\n",
    "siniestros_ajustados = siniestros_incurridos_mes * (1.0 - reduccion_prevencion)\n",
    "\n",
    "loss_ratio = (siniestros_ajustados / ingresos_primas_mes) if ingresos_primas_mes > 0 else 0\n",
    "auto_claims_rate = min(0.96, 0.82 + (adopcion_prevencion * 0.12))\n",
    "margen_tecnico_mes = ingresos_primas_mes - siniestros_ajustados\n",
    "\n",
    "col1, col2, col3, col4 = st.columns(4)\n",
    "col1.metric(\"Primas Mensuales (Primas Devengadas)\", f\"{ingresos_primas_mes:,.0f} €\")\n",
    "col2.metric(\"Loss Ratio (S/P)\", f\"{loss_ratio:.1%}\", delta=f\"Target 78%\", delta_color=\"inverse\")\n",
    "col3.metric(\"Auto-Claims Processing\", f\"{auto_claims_rate:.1%}\")\n",
    "col4.metric(\"Margen Técnico Mensual\", f\"{margen_tecnico_mes:,.0f} €\")\n",
    "\n",
    "st.divider()\n",
    "\n",
    "col_left, col_right = st.columns(2)\n",
    "\n",
    "with col_left:\n",
    "    st.subheader(\"📈 Comparativa de Loss Ratio por Plan de Salud\")\n",
    "    planes_b2b = [\"Essentiel\", \"Balanced\", \"Optimal\"]\n",
    "    primas_b2b = [38*factor_demog, 52*factor_demog, 75*factor_demog]\n",
    "    lr_b2b = [(frecuencia_reclamos * costo_medio_reclamo * (1-reduccion_prevencion)) / p for p in primas_b2b]\n",
    "    \n",
    "    df_lr = pd.DataFrame({\"Plan B2B\": planes_b2b, \"Loss Ratio (%)\": [lr * 100 for lr in lr_b2b]})\n",
    "    fig_lr = px.bar(df_lr, x=\"Plan B2B\", y=\"Loss Ratio (%)\", text_auto=\".1f\", color_discrete_sequence=[\"#00D47E\"])\n",
    "    fig_lr.add_hline(y=78, line_dash=\"dash\", line_color=\"red\", annotation_text=\"Objetivo Target (78%)\")\n",
    "    st.plotly_chart(fig_lr, use_container_width=True)\n",
    "\n",
    "with col_right:\n",
    "    st.subheader(\"🩺 Distribución del Gasto por Categoria Prestacional\")\n",
    "    categorias = [\"Atención Primaria\", \"Especialistas\", \"Salud Mental & Fisio\", \"Hospitalización\"]\n",
    "    pesos = [0.25, 0.35, 0.25, 0.15]\n",
    "    gastos = [siniestros_ajustados * p for p in pesos]\n",
    "    df_cat = pd.DataFrame({\"Categoría\": categorias, \"Gasto Mensual (€)\": gastos})\n",
    "    fig_pie = px.pie(df_cat, names=\"Categoría\", values=\"Gasto Mensual (€)\", color_discrete_sequence=px.colors.qualitative.Set2)\n",
    "    st.plotly_chart(fig_pie, use_container_width=True)\n",
    "\n",
    "st.caption(\"Caso técnico Alan España - Framework de Reporting Actuarial y de Producto.\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4f8508be-096a-480b-8e2a-d2f990fc2409",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "anaconda-2025.12-py312",
   "language": "python",
   "name": "conda-env-anaconda-2025.12-py312-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
