# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MtBB5Bsw3gJrdo0YIqM9ddSMNEKda_uV
"""

!pip install streamlit pandas plotly
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px


st.set_page_config(
    page_title="Alan Health Spain - Monthly Actuarial & Business Reporting",
    page_icon="💚",
    layout="wide"
)

st.title("💚 Alan Health Spain: Reporting Mensual de Rentabilidad y Drivers Actuariales")
st.markdown("""
Framework de reporting interno mensual diseñado bajo los principios de **transparencia radical** de Alan.
Permite monitorizar la cuenta de resultados técnica, los *Key Actuarial Drivers* y la rentabilidad por segmento y producto.
""")

# --- SIDEBAR: CONTEXTO Y OFERTAS OFICIALES DE ALAN ---
st.sidebar.header("🏢 Segmento de Cliente y Oferta")
segmento = st.sidebar.radio("Tipo de Cliente", ["Empresas (B2B)", "Individuales / TNS (B2C)"])

if segmento == "Empresas (B2B)":
    plan = st.sidebar.selectbox("Oferta B2B (Elegible Colectivos)", ["Essentiel", "Balanced", "Optimal"])
    num_miembros = st.sidebar.slider("Número de Asegurados en Colectivo", min_value=50, max_value=10000, value=1000, step=50)
    edad_media = st.sidebar.slider("Edad Media de la Plantilla (Ajuste Demográfico)", min_value=20, max_value=65, value=36)

    # Primas base estimadas B2B
    prima_base = {"Essentiel": 38.0, "Balanced": 52.0, "Optimal": 75.0}[plan]
    # Factor demográfico actuarial B2B (+1.5% por año sobre 30 años base)
    factor_demog = 1.0 + max(0, (edad_media - 30) * 0.015)
    prima_mes = prima_base * factor_demog
else:
    plan = st.sidebar.selectbox("Oferta B2C (Trabajadores No Salariados / TNS)", ["Alan Rubis", "Alan Emeraude", "Alan Saphir"])
    num_miembros = st.sidebar.slider("Número de Asegurados Individuales", min_value=50, max_value=3000, value=500, step=25)
    prima_mes = {"Alan Rubis": 42.0, "Alan Emeraude": 65.0, "Alan Saphir": 95.0}[plan]
    factor_demog = 1.0

st.sidebar.header("📊 Drivers de Siniestralidad y Reservas")
frecuencia_reclamos = st.sidebar.slider("Frecuencia (Reclamos / Miembro / Mes)", min_value=0.2, max_value=2.0, value=0.65, step=0.05)
costo_medio_reclamo = st.sidebar.number_input("Costo Medio por Reclamo (€)", min_value=20.0, max_value=300.0, value=58.0, step=2.0)

# Reservas Actuariales
rbns_pct = st.sidebar.slider("Reserva RBNS (% Siniestros Pendientes Notificados)", min_value=1.0, max_value=8.0, value=3.0, step=0.5) / 100.0
ibnr_pct = st.sidebar.slider("Reserva IBNR (% Siniestros Incurridos No Reportados)", min_value=1.0, max_value=10.0, value=4.5, step=0.5) / 100.0
adopcion_prevencion = st.sidebar.slider("Adopción Salud Digital / Prevención (%)", min_value=10, max_value=100, value=55, step=5) / 100.0

st.sidebar.header("💸 Cargas de Gastos y Operación (% Prima)")
comisiones_pct = st.sidebar.slider("Comisiones / Adquisición (CAC) (%)", min_value=0.0, max_value=15.0, value=4.5, step=0.5) / 100.0
operaciones_admin_pct = st.sidebar.slider("Gastos Admin & Operaciones Ops (%)", min_value=5.0, max_value=20.0, value=9.5, step=0.5) / 100.0
reaseguro_pct = st.sidebar.slider("Costo de Reaseguro / Capital (%)", min_value=0.5, max_value=5.0, value=1.5, step=0.1) / 100.0

# --- CÁLCULOS ACTUARIALES ---
ingresos_primas_mes = num_miembros * prima_mes

# Siniestralidad
siniestros_pagados_base = num_miembros * frecuencia_reclamos * costo_medio_reclamo
reduccion_prevencion = adopcion_prevencion * 0.07 # Reducción por prevención activa
siniestros_pagados = siniestros_pagados_base * (1.0 - reduccion_prevencion)

rbns_monto = siniestros_pagados * rbns_pct
ibnr_monto = (siniestros_pagados + rbns_monto) * ibnr_pct
siniestros_totales_incurridos = siniestros_pagados + rbns_monto + ibnr_monto

# Gastos Operativos y Adquisición
comisiones_monto = ingresos_primas_mes * comisiones_pct
gastos_admin_monto = ingresos_primas_mes * operaciones_admin_pct
reaseguro_monto = ingresos_primas_mes * reaseguro_pct
gastos_totales_monto = comisiones_monto + gastos_admin_monto + reaseguro_monto

# Márgenes y Ratios Actuariales
margen_tecnico_bruto = ingresos_primas_mes - siniestros_totales_incurridos
resultado_tecnico_neto = margen_tecnico_bruto - gastos_totales_monto

loss_ratio = (siniestros_totales_incurridos / ingresos_primas_mes) if ingresos_primas_mes > 0 else 0
expense_ratio = (gastos_totales_monto / ingresos_primas_mes) if ingresos_primas_mes > 0 else 0
combined_ratio = loss_ratio + expense_ratio
auto_claims_rate = min(0.96, 0.82 + (adopcion_prevencion * 0.12))

# --- TARJETAS DE MÉTRICAS CLAVE (KPIs) ---
col1, col2, col3, col4 = st.columns(4)
col1.metric("Primas Devengadas Mes", f"{ingresos_primas_mes:,.0f} €")
col2.metric("Loss Ratio Incurrido (S/P)", f"{loss_ratio:.1%}", delta=f"Target <78%", delta_color="inverse")
col3.metric("Combined Ratio Total", f"{combined_ratio:.1%}", delta=f"{'Superávit' if combined_ratio < 1 else 'Déficit'}", delta_color="inverse")
col4.metric("Resultado Técnico Neto Mes", f"{resultado_tecnico_neto:,.0f} €")

st.divider()

# --- DASHBOARD VISUAL ---
col_left, col_right = st.columns(2)

with col_left:
    st.subheader("📊 Desglose de la Cuenta de Resultados (P&L Actuarial)")
    conceptos = ["Primas Devengadas", "Siniestros Pagados", "Reserva RBNS", "Reserva IBNR", "Gastos Operativos & CAC", "Resultado Neto"]
    valores = [
        ingresos_primas_mes,
        -siniestros_pagados,
        -rbns_monto,
        -ibnr_monto,
        -gastos_totales_monto,
        resultado_tecnico_neto
    ]
    df_pnl = pd.DataFrame({"Concepto": conceptos, "Monto (€)": valores})
    fig_pnl = px.bar(df_pnl, x="Concepto", y="Monto (€)", color="Monto (€)",
                     color_continuous_scale=["#EF4444", "#00D47E"], text_auto=".0f")
    fig_pnl.update_layout(showlegend=False, coloraxis_showscale=False)
    st.plotly_chart(fig_pnl, use_container_width=True)

with col_right:
    st.subheader("📈 Sensibilidad Combined Ratio vs Adopción Preventiva")
    adop_range = np.linspace(0.1, 1.0, 10)
    lr_range = [((siniestros_pagados_base * (1 - (a * 0.07))) * (1 + rbns_pct) * (1 + ibnr_pct)) / prima_mes for a in adop_range]
    cr_range = [lr + expense_ratio for lr in lr_range]

    df_cr = pd.DataFrame({"Adopción Salud Digital (%)": adop_range * 100, "Combined Ratio (%)": np.array(cr_range) * 100})
    fig_cr = px.line(df_cr, x="Adopción Salud Digital (%)", y="Combined Ratio (%)", markers=True, color_discrete_sequence=["#111827"])
    fig_cr.add_hline(y=100, line_dash="dash", line_color="red", annotation_text="Breakeven (100%)")
    fig_cr.add_hline(y=90, line_dash="dash", line_color="#00D47E", annotation_text="Target Alan (90%)")
    st.plotly_chart(fig_cr, use_container_width=True)

# Tabla resumida de Ratios Actuariales
st.subheader("📑 Resumen de Ratios Actuariales y Financieros")
ratios_df = pd.DataFrame({
    "Ratio Actuarial": ["Loss Ratio Incurrido (Siniestralidad Total / Primas)", "Expense Ratio (Gastos Admin + Comisiones / Primas)", "Combined Ratio (LR + ER)", "Tasa de Automatización de Siniestros (Auto-claims)"],
    "Valor Calculado": [f"{loss_ratio:.2%}", f"{expense_ratio:.2%}", f"{combined_ratio:.2%}", f"{auto_claims_rate:.1%}"],
    "Benchmark / Target Alan": ["< 78.0%", "< 12.0%", "< 90.0%", "> 90.0%"],
    "Estado": ["✅ En Rango" if loss_ratio <= 0.78 else "⚠️ Revisar Tarifa",
               "✅ Eficiente" if expense_ratio <= 0.15 else "⚠️ Alto G&A",
               "🟢 Rentable" if combined_ratio <= 1.0 else "🔴 En Pérdida",
               "🟢 Objetivo Cumplido" if auto_claims_rate >= 0.9 else "🟡 Mejorar Adopción"]
})
st.table(ratios_df)

st.caption("Alan Health Insurance - Framework de Reporting Actuarial y de Producto v3.0.")